### ISSUE TITLE
Offline/Development server

### ISSUE THREAD

**Issue by justingreenberg** [elastic-coders/serverless-runtime-webpack#8]
Have you guys considered adding `webpack-dev-server`?

The de-facto solutions for offline lambda/API gateway simulation seem to be:
#### **[`serverless-offline`](https://github.com/dherault/serverless-offline)**

unfortunately this [does not support custom runtimes other than babel](https://github.com/dherault/serverless-offline/blob/master/src/index.js#L245) and uses hapi server... runs browserify build on each request. there may be an opportunity to add webpack runtime support and use this package for offline support, but that would mean running compiler on each request as opposed to leveraging webpack's internal server
#### **[`serverless-serve`](https://github.com/Nopik/serverless-serve)**

this uses express under the hood, looks like a good platform for adding [`webpack-dev-middleware`](https://github.com/webpack/webpack-dev-middleware) and maybe even [`webpack-hot-middleware`](https://github.com/glenjamin/webpack-hot-middleware) for hot module replacement :) this seems like the ideal outcome

In my mind webpack is the ideal solution for managing serverless projects.... you guys are def on the right track. Wishlist:
- development server with entries for each handler, hot module replacement
- tree shaking and native es module support without babel (webpack v2)
- common code chunking/merging, etc
- resolver aliasing for shared libs 

Let me know what you guys think! Thanks again for the great work

**Comment by thenikso** [comment]
interesting ideas. at this point it would make sense for me to start working on these in the new https://github.com/elastic-coders/serverless-webpack for Serverless 1.0.

I think that webpack 2 support will totally be a thing when it comes out of beta. the dev-server to serve simil api gateway requests if intriguing.
